spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pool?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: zxw123
    driver-class-name: com.mysql.cj.jdbc.Driver

jackson:
  time-zone: GMT+8

server:
  port: 8084
